[helpers]

[settings]
default_target_type = "symbolic"

[cliphist.files]
"dotfiles/cliphist" = "~/.config/cliphist"

[flameshot.files]
"dotfiles/flameshot" = "~/.config/flameshot"

[hypr.files]
"dotfiles/hypr" = "~/.config/hypr"

[nvim.files]
"dotfiles/neovim.files" = "~/.config/nvim"

[rofi.files]
"dotfiles/rofi" = "~/.config/rofi"

[systemd.files]
"dotfiles/systemd" = "~/.config/systemd"

[waybar.files]
"dotfiles/waybar" = "~/.config/waybar"

[waybar_laptop.files]
"dotfiles/waybar-laptop/config.jsonc" = "~/.config/waybar/config.jsonc"

[wezterm.files]
"dotfiles/wezterm" = "~/.config/wezterm"

[wlogout.files]
"dotfiles/wlogout" = "~/.config/wlogout"

[alsoftrc.files]
"dotfiles/.alsoftrc" = "~/.alsoftrc"

[tmux.files]
"dotfiles/.tmux.conf" = "~/.tmux.conf"

[zsh.files]
"dotfiles/.zsh_profile" = "~/.zsh_profile"
"dotfiles/.zshrc" = "~/.zshrc"

[mime.files]
"dotfiles/mimeapps.list" = "~/.config/mimeapps.list"

[ssh.files]
"dotfiles/ssh/config" = "~/.ssh/config"
"dotfiles/ssh/id_rsa" = "~/.ssh/id_rsa"
"dotfiles/ssh/id_rsa.pub" = "~/.ssh/id_rsa.pub"
"dotfiles/ssh/id_rsa_srv2" = "~/.ssh/id_rsa_srv2"
"dotfiles/ssh/id_rsa_srv2.pub" = "~/.ssh/id_rsa_srv2.pub"
"dotfiles/ssh/storage_server" = "~/.ssh/storage_server"
"dotfiles/ssh/storage_server.pub" = "~/.ssh/storage_server.pub"
"dotfiles/ssh/id_ed25519_test" = "~/.ssh/id_ed25519_test"
"dotfiles/ssh/id_ed25519_test.pub" = "~/.ssh/id_ed25519_test.pub"

[wojk_ssh.files]
"dotfiles/wojk/ssh/poslovni_id_ed25519" = "~/.ssh/poslovni_id_ed25519"
"dotfiles/wojk/ssh/poslovni_id_ed25519.pub" = "~/.ssh/poslovni_id_ed25519.pub"
"dotfiles/wojk/ssh/poslovni_id_phobos_ed25519" = "~/.ssh/poslovni_id_phobos_ed25519"
"dotfiles/wojk/ssh/poslovni_id_phobos_ed25519.pub" = "~/.ssh/poslovni_id_phobos_ed25519.pub"

[wojk_ssh_config.files]
"dotfiles/wojk/ssh/config" = "~/.ssh/config"
