includes = []
packages = [
    "cliphist",
    "flameshot",
    "hypr",
    "nvim",
    "rofi",
    "systemd",
    "waybar",
    "wezterm",
    "alsoftrc",
    "tmux",
    "zsh",
    "mime",
    "ssh",
]

[files]

[variables]
